site_name: <span>FastAPI</span> Debug Toolbar
site_description: A debug toolbar for FastAPI.
site_url: https://debug-toolbar.domake.io

repo_name: mongkok/fastapi-debug-toolbar
repo_url: https://github.com/mongkok/fastapi-debug-toolbar
edit_uri: ''

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github-alt
  palette:
  - scheme: default
    primary: red
    accent: red

nav:
  - Introduction: index.md
  - Built-in panels: panels/built-in.md
  - Development: panels/dev.md
  - Settings: settings.md
  - Changelog: changelog.md

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/mongkok

extra_css:
- css/styles.css

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list
  - markdown_include.include:
      base_path: docs

plugins:
  - search
  - mkdocstrings
