name: Docs

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: "3.12"

      - name: Install dependencies
        run: pip install .[doc]

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
